/*  =========================================================================
    ziflist - List of network interfaces available on system

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of CZMQ, the high-level C binding for 0MQ:
    http://czmq.zeromq.org.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

public import c.zmq.czmq_library;

extern (C):

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/ziflist.api" to make changes.
//  @interface
//  This is a stable class, and may not change except for emergencies. It
//  is provided in stable builds.
//  Get a list of network interfaces currently defined on the system
ziflist_t* ziflist_new ();

//  Destroy a ziflist instance
void ziflist_destroy (ziflist_t** self_p);

//  Reload network interfaces from system
void ziflist_reload (ziflist_t* self);

//  Return the number of network interfaces on system
size_t ziflist_size (ziflist_t* self);

//  Get first network interface, return NULL if there are none
const(char)* ziflist_first (ziflist_t* self);

//  Get next network interface, return NULL if we hit the last one
const(char)* ziflist_next (ziflist_t* self);

//  Return the current interface IP address as a printable string
const(char)* ziflist_address (ziflist_t* self);

//  Return the current interface broadcast address as a printable string
const(char)* ziflist_broadcast (ziflist_t* self);

//  Return the current interface network mask as a printable string
const(char)* ziflist_netmask (ziflist_t* self);

//  Return the list of interfaces.
void ziflist_print (ziflist_t* self);

//  Self test of this class.
void ziflist_test (bool verbose);

//  @end

