#
# Docker file for Laniakea CI
#
FROM debian:bullseye

# prepare
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-native-deps.sh /build/ci/
RUN chmod +x /build/ci/install-native-deps.sh && /build/ci/install-native-deps.sh

# finish
WORKDIR /build
